### ISSUE TITLE
Handling of sextractor errors

### ISSUE THREAD

**Issue by ppapadeas** [cbassa/stvid#57]
Getting 

```
multiprocessing.pool.RemoteTraceback: s...
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "./process.py", line 54, in process_loop
    pix_catalog = generate_star_catalog(fname)
  File "/home/liknus/git/stvid/stvid/stars.py", line 45, in generate_star_catalog
    output = subprocess.check_output(command, shell=True,
  File "/usr/lib64/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sextractor 2020-02-07T19:13:00.714.fits -c /home/liknus/git/sattools/sextractor/default.sex -CATALOG_NAME 2020-02-07T19:13:00.714.fits.cat ' returned non-zero exit status 1.
"""
```
when frame is not optimal (noisy or cloudy)

**Comment by cbassa** [comment]
These `sextractor` errors can also be caused by a collision between the FITS file being not completely written while `sextractor` tries to write it.

**Comment by cbassa** [comment]
Solved with new processing implementation.
